<!DOCTYPE html>
<html lang="fr">
<head>
  <title>Bienvenue sur «BAHHZ»</title>
  <meta charset="UTF-8">
  <style type="text/css">
      #main { margin-top: 80px;  }
  </style>
  <link href="./assets/pygments.css" rel="stylesheet">
  <link href="./assets/bootstrap/css/bootstrap.css" rel="stylesheet">
  <link href="./assets/bootstrap/css/bootstrap-responsive.css" rel="stylesheet"> 
  <link href="./assets/google-code-prettify/prettify.css" type="text/css" rel="stylesheet"/>
  <script type="text/javascript" src="./assets/google-code-prettify/prettify.js"></script>
</head><body style="background-color:#FFFFFF;" onload="prettyPrint()">
<div class="navbar navbar-fixed-top">
  <div class="navbar-inner">
    <div class="container">
      <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </a>
      <a class="brand" href="./index.html" style="margin: 0; margin-right: 30px; margin-top: 3px; padding:0;">
        <img alt="logo" src="./logo-original.jpg" style="height: 35px; padding: 0; margin: 0;"/><img alt="nom" src="./titre-du-jeu.jpg" style="height: 35px; padding: 0; margin: 0;"/>
      </a>
      <div class="nav-collapse">
        <ul class="nav">
          <li class="active"><a href="./notrejeu.htm">Lancer le jeu</a></li>
          <li><a href="./apropos.htm">À propos du jeu</a></li>
          <li><a href="./credits.htm">Crédits</a></li>
          <li>
<!-- AddThis Button BEGIN -->
<a class="addthis_button" href="http://www.addthis.com/bookmark.php?v=250&amp;pubid=xa-5040d001207fbc52"><img src="http://s7.addthis.com/static/btn/v2/lg-share-en.gif" width="125" height="16" alt="Bookmark and Share" style="border:0"/></a>
<script type="text/javascript" src="http://s7.addthis.com/js/250/addthis_widget.js#pubid=xa-5040d001207fbc52"></script>
<!-- AddThis Button END -->
          </li>
          <li><a href="./notrejeu.jvs.htm">Le programme</a></li>
          <li><a href="./notrejeu.zip">Téléchargement</a></li>
          <li><a href="mailto:?subject=éclate toi aussi avec notre petit jeu «BAHHZ»&body=http://www-sop.inria.fr/science-participative/bahhz">Partager le lien</a></li>
        </ul>
      </div>
    </div>
  </div>
</div>
<div class="container" id="main">

