/* Automatically generated by the makefile: DO NOT EDIT !*/ package org.javascool;
class hdoc2htm { static String xsl =
                   "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n" +
                   "<xsl:stylesheet version=\"1.0\" xmlns:xsl=\"http://www.w3.org/1999/XSL/Transform\">\n" +
                   "\n" +
                   "  <!-- This XSLT translates the proglet's HML documentation to HTML3.2 http://www.w3.org/TR/REC-html32-19970114) -->\n" +
                   "\n" +
                   "  <xsl:import href=\"./hml2htm.xslt\"/>\n" +
                   "\n" +
                   "<!-- These tags produce javasccool's doc specific constructs -->\n" +
                   "\n" +
                   "<xsl:template match=\"div|p\">\n" +
                   "  <xsl:choose>\n" +
                   "    <xsl:when test=\"@class = 'sujet'\">\n" +
                   "      <div align=\"right\">\n" +
                   "        <xsl:if test =\"count(intros) > 0\">[<a href=\"#intros\">introduction</a>]</xsl:if>\n" +
                   "        <xsl:if test =\"count(works) > 0\">[<a href=\"#works\">travail proposé</a>]</xsl:if>\n" +
                   "        <xsl:if test =\"count(notes) > 0\">[<a href=\"#notes\">remarques</a>]</xsl:if>\n" +
                   "      </div>\n" +
                   "      <xsl:call-template name=\"div\"/>\n" +
                   "    </xsl:when>\n" +
                   "    <xsl:when test=\"@class = 'objectif'\"><h2>Objectif.</h2><xsl:call-template name=\"div\"/></xsl:when>\n" +
                   "    <xsl:when test=\"@class = 'intros' or @class = 'works' or @class = 'notes'\">\n" +
                   "      <xsl:choose>\n" +
                   "        <xsl:when test=\"@class = 'intros'\"><h2>Introduction.</h2></xsl:when>\n" +
                   "        <xsl:when test=\"@class = 'works'\"><h2>Travail proposé.</h2></xsl:when>\n" +
                   "        <xsl:when test=\"@class = 'notes'\"><h2>Remarques.</h2></xsl:when>\n" +
                   "      </xsl:choose>\n" +
                   "      <div id=\"{@class}\"><ol><xsl:for-each select=\"*\"><li><xsl:call-template name=\"div\"/></li></xsl:for-each></ol></div>\n" +
                   "    </xsl:when>\n" +
                   "    <xsl:when test=\"@class = 'code'\"><p><table witdh=\"90%\" border=\"1\" align=\"center\"><tr><td><xsl:call-template name=\"div\"/></td></tr></table></p></xsl:when>\n" +
                   "    <xsl:otherwise><xsl:call-template name=\"div\"/></xsl:otherwise>\n" +
                   "  </xsl:choose>\n" +
                   "</xsl:template>\n" +
                   "\n" +
                   "<xsl:template match=\"l\">\n" +
                   "  <xsl:choose>\n" +
                   "    <xsl:when test=\"@class = 'javascool'\"><tt><a href=\"http://javascool.gforge.inria.fr\" style=\"padding:0;margin:0;text-decoration:none\">Java'sCool</a></tt></xsl:when>\n" +
                   "    <xsl:when test=\"@class = 'proglet'\">\n" +
                   "      <applet code=\"org.javascool.ProgletApplet\" archive=\"http://javascool.gforge.inria.fr/v3/javascool.jar\" width=\"560\" height=\"720\">\n" +
                   "        <param name=\"proglet\" value=\"{@link}\"/>\n" +
                   "      </applet>\n" +
                   "    </xsl:when>\n" +
                   "    <xsl:when test=\"@class = 'note'\"><sup><a href=\"{concat('#', @link)}\"><xsl:value-of select=\"@link\"/></a></sup></xsl:when>\n" +
                   "    <xsl:otherwise><xsl:call-template name=\"l\"/></xsl:otherwise>\n" +
                   "  </xsl:choose>\n" +
                   "</xsl:template>\n" +
                   "\n" +
                   "<!-- These tags allows to show pieces of code -->\n" +
                   "\n" +
                   "<xsl:template match=\"r\">\n" +
                   "  <font color=\"#990000\"><b><xsl:apply-templates/></b></font>\n" +
                   "</xsl:template>\n" +
                   "\n" +
                   "<xsl:template match=\"n\">\n" +
                   "  <font color=\"#505000\"><xsl:apply-templates/></font>\n" +
                   "</xsl:template>\n" +
                   "\n" +
                   "<xsl:template match=\"v\">\n" +
                   "  <font color=\"#008000\">&quot;<xsl:apply-templates/>&quot;</font>\n" +
                   "</xsl:template>\n" +
                   "\n" +
                   "<xsl:template match=\"m\">\n" +
                   "  <p><tt><font color=\"#202080\"><big>//</big>&#160;<xsl:apply-templates/></font></tt></p>\n" +
                   "</xsl:template>\n" +
                   "\n" +
                   "<xsl:template match=\"T\">\n" +
                   "  &#160;&#160;&#160;\n" +
                   "</xsl:template>\n" +
                   "\n" +
                   "</xsl:stylesheet>\n" +
                   "";
}
