/* Automatically generated by the makefile: DO NOT EDIT !*/ package org.javascool; class htm2hml { static String xsl = 
"<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n"+
"<xsl:stylesheet version=\"1.0\" xmlns:xsl=\"http://www.w3.org/1999/XSL/Transform\">\n"+
"\n"+
"  <!-- This XSLT translates HTNML to HML constructs -->\n"+
"\n"+
"<xsl:output method=\"xml\" encoding=\"utf-8\" omit-xml-declaration=\"yes\"/>\n"+
"\n"+
"<!--- 1: Division translation -->\n"+
"\n"+
"<xsl:template match=\"ul|ol|table\">\n"+
"  <div class=\"{name(.)}\"> \n"+
"    <xsl:apply-templates/>\n"+
"  </div>\n"+
"</xsl:template>\n"+
"\n"+
"<xsl:template match=\"div|p|li|tr|td\">\n"+
"  <div>\n"+
"    <xsl:if test=\"count(@title)=1\"><xsl:attribute name=\"title\"><xsl:value-of select=\"@title\"/></xsl:attribute></xsl:if>\n"+
"    <xsl:choose>\n"+
"      <xsl:when test=\"count(@class)=1\"><xsl:attribute name=\"class\"><xsl:value-of select=\"@class\"/></xsl:attribute></xsl:when>\n"+
"      <xsl:when test=\"count(@align)=1\"><xsl:attribute name=\"class\"><xsl:value-of select=\"@align\"/></xsl:attribute></xsl:when>\n"+
"      <xsl:when test=\"count(@valign)=1\"><xsl:attribute name=\"class\"><xsl:value-of select=\"@valign\"/></xsl:attribute></xsl:when>\n"+
"    </xsl:choose>\n"+
"    <xsl:if test=\"count(@id)=1\"><xsl:attribute name=\"id\"><xsl:value-of select=\"@id\"/></xsl:attribute></xsl:if>\n"+
"    <xsl:apply-templates/>\n"+
"  </div>\n"+
"</xsl:template>\n"+
"\n"+
"<!--- 2: Span translation -->\n"+
"\n"+
"<xsl:template match=\"span\">\n"+
"  <s>    \n"+
"    <xsl:if test=\"count(@class)=1\"><xsl:attribute name=\"class\"><xsl:value-of select=\"class\"/></xsl:attribute></xsl:if>\n"+
"    <xsl:apply-templates/>\n"+
"  </s>\n"+
"</xsl:template>\n"+
"<xsl:template match=\"b|i|u\">\n"+
"  <xsl:element name=\"{name(.)}\"><xsl:apply-templates/></xsl:element>\n"+
"</xsl:template>\n"+
"<xsl:template match=\"tt\"><c><xsl:apply-templates/></c></xsl:template>\n"+
"<xsl:template match=\"sup\"><S><xsl:apply-templates/></S></xsl:template>\n"+
"<xsl:template match=\"sub\"><I><xsl:apply-templates/></I></xsl:template>\n"+
"\n"+
"<!--- 3: Link translation -->\n"+
"\n"+
"<xsl:template match=\"a\">\n"+
"  <l>    \n"+
"    <xsl:if test=\"count(@class)=1\"><xsl:attribute name=\"class\"><xsl:value-of select=\"class\"/></xsl:attribute></xsl:if>\n"+
"    <xsl:if test=\"count(@href)=1\"><xsl:attribute name=\"link\"><xsl:value-of select=\"@href\"/></xsl:attribute></xsl:if>\n"+
"    <xsl:if test=\"count(img/@src)=1\"><xsl:attribute name=\"icon\"><xsl:value-of select=\"img/@src\"/></xsl:attribute></xsl:if>\n"+
"    <xsl:attribute name=\"text\"><xsl:value-of select=\"text()\"/></xsl:attribute>\n"+
"  </l>\n"+
"</xsl:template>\n"+
"\n"+
"<xsl:template match=\"img\">\n"+
"  <l class=\"icon\">    \n"+
"    <xsl:if test=\"count(@src)=1\"><xsl:attribute name=\"icon\"><xsl:value-of select=\"@src\"/></xsl:attribute></xsl:if>\n"+
"    <xsl:if test=\"count(@alt)=1\"><xsl:attribute name=\"text\"><xsl:value-of select=\"@alt\"/></xsl:attribute></xsl:if>\n"+
"  </l>\n"+
"</xsl:template>\n"+
"\n"+
"<!--- 4: Spurious translation -->\n"+
"\n"+
"<xsl:template match=\"br|hr|form|input|select|option\">\n"+
"  <xsl:message>Unexpected tag: <xsl:value-of select=\"name(.)\"/> !!</xsl:message>\n"+
"</xsl:template>\n"+
"\n"+
"<xsl:template match=\"*\">\n"+
"  <xsl:message>Undefined tag: <xsl:value-of select=\"name(.)\"/> !!</xsl:message>\n"+
"</xsl:template>\n"+
"\n"+
"</xsl:stylesheet>\n"+
"";}
