
ifeq ($(USER), vthierry)

all : 
	@$(MAKE) j3
#	@cd ../tst ; ../lib/run.sh org.javascool.AlgoEditor
#	@cd ../tst ; ../lib/run.sh org.javascool.ProgletApplet exosdemaths

endif

j3 :
	@$(MAKE) -C ../../.. j3
