/* Automatically generated by the makefile: DO NOT EDIT !*/ package org.javascool; class pml2htm { static String xsl = 
"<?xml version='1.0' encoding='utf-8'?>\n"+
"<xsl:stylesheet xmlns:xsl='http://www.w3.org/1999/XSL/Transform' version='1.0'>\n"+
"  <xsl:output method='html' encoding='utf-8'/>\n"+
"  <xsl:template match='l'><xsl:element name='a'>\n"+
"    <xsl:if test='count(@class) > 0'><xsl:attribute name='class'><xsl:value-of select='@class'/></xsl:attribute></xsl:if>\n"+
"    <xsl:if test='count(@link) > 0'><xsl:attribute name='href'><xsl:value-of select='@link'/></xsl:attribute></xsl:if>\n"+
"    <xsl:value-of select='@text'/>\n"+
"  </xsl:element></xsl:template>\n"+
"  <xsl:template match='s'><xsl:element name='span'>\n"+
"    <xsl:if test='count(@class) > 0'><xsl:attribute name='class'><xsl:value-of select='@class'/></xsl:attribute></xsl:if>\n"+
"    <xsl:apply-templates/>\n"+
"  </xsl:element></xsl:template>\n"+
"  <xsl:template match='*'><xsl:element name='{name(.)}'>\n"+
"    <xsl:for-each select='@*'><xsl:attribute name='{name(.)}'><xsl:value-of select='.'/></xsl:attribute></xsl:for-each>\n"+
"    <xsl:apply-templates/>\n"+
"  </xsl:element></xsl:template>\n"+
"</xsl:stylesheet>\n"+
"";}
