/* Automatically generated by the makefile: DO NOT EDIT !*/ package org.javascool; class proglets { static String proglets[] = {
"proglet.synthesons.SoundDisplay",
"proglet.convanalogique.ConvAnalogique",
"proglet.tortuelogo.TortueLogo",
"proglet.ingredients.Console",
"proglet.pixelsetcie.ImageDisplay",
"proglet.javaprog.JavaPanel",
"proglet.joueraveclestextes.GrandsTextes",
"proglet.dichotomie.Dichotomie",
"proglet.exosdemaths.CurveDisplay",
"proglet.joueravecleschiffres.MacrosChiffre",
"proglet.goglemap.GogleMap",
"proglet.paintbrush.PaintBrush",
""}; }
