/* Automatically generated by the makefile: DO NOT EDIT !*/ package org.javascool; class proglets { static String proglets[] = {
"proglet.exosdemaths.CurveDisplay",
"proglet.synthesons.SoundDisplay",
"proglet.dichotomie.Dichotomie",
"proglet.convanalogique.ConvAnalogique",
"proglet.pixelsetcie.ImageDisplay",
"proglet.tortuelogo.TortueLogo",
"proglet.ingredients.Console",
"proglet.javaprog.JavaPanel",
""}; }
