/* Automatically generated by the makefile: DO NOT EDIT !*/ package org.javascool; class Proglets { static String proglets[] = {
"proglet.synthesons.SoundDisplay",
"proglet.convanalogique.ConvAnalogique",
"proglet.tortuelogo.TortueLogo",
"proglet.ingredients.Console",
"proglet.dichotomie.Dichotomie",
"proglet.exosdemaths.DisplayCurve",
"proglet.javaprog.JavaPanel",
"proglet.pixelsetcie.ImageDisplay",
""}; }
