/*******************************************************************************
 * Thierry.Vieville@sophia.inria.fr, Copyright (C) 2009.  All rights reserved. *
 *******************************************************************************/

//package org.javascool.dicho;

// Used to define the gui
import javax.swing.JPanel;

// Used to define an icon
import javax.swing.JLabel;
import javax.swing.ImageIcon;

/** Defines a javascool panel which allows to experiment with the dichotomic search. */
public class Dicho extends JPanel {
  /** Constructs the panel. */
  public Dicho() {
    // Adds the background icon
    JLabel icon = new JLabel(); icon.setIcon(new ImageIcon("../img/vieuxlivre.jpg")); add(icon);
  }

  private static String dicho[][] = {
    { "Afghanistan", "http://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Flag_of_Afghanistan.svg/20px-Flag_of_Afghanistan.svg.png", "http://fr.wikipedia.org/wiki/Afghanistan" },  
    { "Afrique du Sud", "http://upload.wikimedia.org/wikipedia/commons/thumb/a/af/Flag_of_South_Africa.svg/20px-Flag_of_South_Africa.svg.png", "http://fr.wikipedia.org/wiki/Afrique_du_Sud" },  
    { "Albanie", "http://upload.wikimedia.org/wikipedia/commons/thumb/3/36/Flag_of_Albania.svg/20px-Flag_of_Albania.svg.png", "http://fr.wikipedia.org/wiki/Albanie" },  
    { "Algérie", "http://upload.wikimedia.org/wikipedia/commons/thumb/7/77/Flag_of_Algeria.svg/20px-Flag_of_Algeria.svg.png", "http://fr.wikipedia.org/wiki/Alg%C3%A9rie" },     
    { "Allemagne", "http://upload.wikimedia.org/wikipedia/commons/thumb/b/ba/Flag_of_Germany.svg/20px-Flag_of_Germany.svg.png", "http://fr.wikipedia.org/wiki/Allemagne" },  
    { "Andorre", "http://upload.wikimedia.org/wikipedia/commons/thumb/1/19/Flag_of_Andorra.svg/20px-Flag_of_Andorra.svg.png", "http://fr.wikipedia.org/wiki/Andorre" },  
    { "Angola", "http://upload.wikimedia.org/wikipedia/commons/thumb/9/9d/Flag_of_Angola.svg/20px-Flag_of_Angola.svg.png", "http://fr.wikipedia.org/wiki/Angola" },      
    { "Antigua-et-Barbuda", "http://upload.wikimedia.org/wikipedia/commons/thumb/8/89/Flag_of_Antigua_and_Barbuda.svg/20px-Flag_of_Antigua_and_Barbuda.svg.png", "http://fr.wikipedia.org/wiki/Antigua-et-Barbuda" },    
    { "Arabie saoudite", "http://upload.wikimedia.org/wikipedia/commons/thumb/0/0d/Flag_of_Saudi_Arabia.svg/20px-Flag_of_Saudi_Arabia.svg.png", "http://fr.wikipedia.org/wiki/Arabie_saoudite" },    
    { "Argentine", "http://upload.wikimedia.org/wikipedia/commons/thumb/1/1a/Flag_of_Argentina.svg/20px-Flag_of_Argentina.svg.png", "http://fr.wikipedia.org/wiki/Argentine" },    
    { "Arménie", "http://upload.wikimedia.org/wikipedia/commons/thumb/2/2f/Flag_of_Armenia.svg/20px-Flag_of_Armenia.svg.png", "http://fr.wikipedia.org/wiki/Arm%C3%A9nie" },    
    { "Australie", "http://upload.wikimedia.org/wikipedia/commons/thumb/b/b9/Flag_of_Australia.svg/20px-Flag_of_Australia.svg.png", "http://fr.wikipedia.org/wiki/Australie" },    
    { "Autriche", "http://upload.wikimedia.org/wikipedia/commons/thumb/4/41/Flag_of_Austria.svg/20px-Flag_of_Austria.svg.png", "http://fr.wikipedia.org/wiki/Autriche" },    
    { "Azerbaïdjan", "http://upload.wikimedia.org/wikipedia/commons/thumb/d/dd/Flag_of_Azerbaijan.svg/20px-Flag_of_Azerbaijan.svg.png", "http://fr.wikipedia.org/wiki/Azerba%C3%AFdjan" },    
    { "Bahamas", "http://upload.wikimedia.org/wikipedia/commons/thumb/9/93/Flag_of_the_Bahamas.svg/20px-Flag_of_the_Bahamas.svg.png", "http://fr.wikipedia.org/wiki/Bahamas" },    
    { "Bahreïn", "http://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Flag_of_Bahrain.svg/20px-Flag_of_Bahrain.svg.png", "http://fr.wikipedia.org/wiki/Bahre%C3%AFn" },    
    { "Bangladesh", "http://upload.wikimedia.org/wikipedia/commons/thumb/f/f9/Flag_of_Bangladesh.svg/20px-Flag_of_Bangladesh.svg.png", "http://fr.wikipedia.org/wiki/Bangladesh" },    
    { "Barbade", "http://upload.wikimedia.org/wikipedia/commons/thumb/e/ef/Flag_of_Barbados.svg/20px-Flag_of_Barbados.svg.png", "http://fr.wikipedia.org/wiki/Barbade" },    
    { "Belgique", "http://upload.wikimedia.org/wikipedia/commons/thumb/9/92/Flag_of_Belgium_%28civil%29.svg/20px-Flag_of_Belgium_%28civil%29.svg.png", "http://fr.wikipedia.org/wiki/Belgique" },    
    { "Belize", "http://upload.wikimedia.org/wikipedia/commons/thumb/e/e7/Flag_of_Belize.svg/20px-Flag_of_Belize.svg.png", "http://fr.wikipedia.org/wiki/Belize" },    
    { "Bénin", "http://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Flag_of_Benin.svg/20px-Flag_of_Benin.svg.png", "http://fr.wikipedia.org/wiki/B%C3%A9nin" },    
    { "Bhoutan", "http://upload.wikimedia.org/wikipedia/commons/thumb/9/91/Flag_of_Bhutan.svg/20px-Flag_of_Bhutan.svg.png", "http://fr.wikipedia.org/wiki/Bhoutan" },    
    { "Biélorussie", "http://upload.wikimedia.org/wikipedia/commons/thumb/8/85/Flag_of_Belarus.svg/20px-Flag_of_Belarus.svg.png", "http://fr.wikipedia.org/wiki/Bi%C3%A9lorussie" },    
    { "Myanmar", "http://upload.wikimedia.org/wikipedia/commons/thumb/8/8c/Flag_of_Myanmar.svg/20px-Flag_of_Myanmar.svg.png", "http://fr.wikipedia.org/wiki/Birmanie" },    
    { "Bolivie", "http://upload.wikimedia.org/wikipedia/commons/thumb/d/de/Flag_of_Bolivia_%28state%29.svg/20px-Flag_of_Bolivia_%28state%29.svg.png", "http://fr.wikipedia.org/wiki/Bolivie" },    
    { "Bosnie-Herzégovine", "http://upload.wikimedia.org/wikipedia/commons/thumb/b/bf/Flag_of_Bosnia_and_Herzegovina.svg/20px-Flag_of_Bosnia_and_Herzegovina.svg.png", "http://fr.wikipedia.org/wiki/Bosnie-Herz%C3%A9govine" },    
    { "Botswana", "http://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Flag_of_Botswana.svg/20px-Flag_of_Botswana.svg.png", "http://fr.wikipedia.org/wiki/Botswana" },    
    { "Brésil", "http://upload.wikimedia.org/wikipedia/commons/thumb/0/05/Flag_of_Brazil.svg/20px-Flag_of_Brazil.svg.png", "http://fr.wikipedia.org/wiki/Br%C3%A9sil" },    
    { "Brunei", "http://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/Flag_of_Brunei.svg/20px-Flag_of_Brunei.svg.png", "http://fr.wikipedia.org/wiki/Brunei" },    
    { "Bulgarie", "http://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Flag_of_Bulgaria.svg/20px-Flag_of_Bulgaria.svg.png", "http://fr.wikipedia.org/wiki/Bulgarie" },    
    { "Burkina Faso", "http://upload.wikimedia.org/wikipedia/commons/thumb/3/31/Flag_of_Burkina_Faso.svg/20px-Flag_of_Burkina_Faso.svg.png", "http://fr.wikipedia.org/wiki/Burkina" },    
    { "Burundi", "http://upload.wikimedia.org/wikipedia/commons/thumb/5/50/Flag_of_Burundi.svg/20px-Flag_of_Burundi.svg.png", "http://fr.wikipedia.org/wiki/Burundi" },    
    { "Cambodge", "http://upload.wikimedia.org/wikipedia/commons/thumb/8/83/Flag_of_Cambodia.svg/20px-Flag_of_Cambodia.svg.png", "http://fr.wikipedia.org/wiki/Cambodge" },    
    { "Cameroun", "http://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Flag_of_Cameroon.svg/20px-Flag_of_Cameroon.svg.png", "http://fr.wikipedia.org/wiki/Cameroun" },    
    { "Canada", "http://upload.wikimedia.org/wikipedia/commons/thumb/c/cf/Flag_of_Canada.svg/20px-Flag_of_Canada.svg.png", "http://fr.wikipedia.org/wiki/Canada" },    
    { "Cap-Vert", "http://upload.wikimedia.org/wikipedia/commons/thumb/3/38/Flag_of_Cape_Verde.svg/20px-Flag_of_Cape_Verde.svg.png", "http://fr.wikipedia.org/wiki/Cap-Vert" },    
    { "Centrafrique", "http://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Flag_of_the_Central_African_Republic.svg/20px-Flag_of_the_Central_African_Republic.svg.png", "http://fr.wikipedia.org/wiki/R%C3%A9publique_centrafricaine" },    
    { "Chili", "http://upload.wikimedia.org/wikipedia/commons/thumb/7/78/Flag_of_Chile.svg/20px-Flag_of_Chile.svg.png", "http://fr.wikipedia.org/wiki/Chili" },    
    { "République populaire de Chine", "http://upload.wikimedia.org/wikipedia/commons/thumb/f/fa/Flag_of_the_People%27s_Republic_of_China.svg/20px-Flag_of_the_People%27s_Republic_of_China.svg.png", "http://fr.wikipedia.org/wiki/R%C3%A9publique_populaire_de_Chine" },    
    { "Chypre", "http://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/Flag_of_Cyprus.svg/20px-Flag_of_Cyprus.svg.png", "http://fr.wikipedia.org/wiki/Chypre_%28pays%29" },    
    { "Colombie", "http://upload.wikimedia.org/wikipedia/commons/thumb/2/21/Flag_of_Colombia.svg/20px-Flag_of_Colombia.svg.png", "http://fr.wikipedia.org/wiki/Colombie" },    
    { "Comores", "http://upload.wikimedia.org/wikipedia/commons/thumb/9/94/Flag_of_the_Comoros.svg/20px-Flag_of_the_Comoros.svg.png", "http://fr.wikipedia.org/wiki/Union_des_Comores" },    
    { "République démocratique du Congo", "http://upload.wikimedia.org/wikipedia/commons/thumb/6/6f/Flag_of_the_Democratic_Republic_of_the_Congo.svg/20px-Flag_of_the_Democratic_Republic_of_the_Congo.svg.png", "http://fr.wikipedia.org/wiki/R%C3%A9publique_d%C3%A9mocratique_du_Congo" },    
    { "Congo-Brazzaville", "http://upload.wikimedia.org/wikipedia/commons/thumb/9/92/Flag_of_the_Republic_of_the_Congo.svg/20px-Flag_of_the_Republic_of_the_Congo.svg.png", "http://fr.wikipedia.org/wiki/R%C3%A9publique_du_Congo" },    
    { "Corée du Nord", "http://upload.wikimedia.org/wikipedia/commons/thumb/5/51/Flag_of_North_Korea.svg/20px-Flag_of_North_Korea.svg.png", "http://fr.wikipedia.org/wiki/Cor%C3%A9e_du_Nord" },    
    { "Corée du Sud", "http://upload.wikimedia.org/wikipedia/commons/thumb/0/09/Flag_of_South_Korea.svg/20px-Flag_of_South_Korea.svg.png", "http://fr.wikipedia.org/wiki/Cor%C3%A9e_du_Sud" },    
    { "Costa Rica", "http://upload.wikimedia.org/wikipedia/commons/thumb/f/f2/Flag_of_Costa_Rica.svg/20px-Flag_of_Costa_Rica.svg.png", "http://fr.wikipedia.org/wiki/Costa_Rica" },    
    { "Côte d'Ivoire", "http://upload.wikimedia.org/wikipedia/commons/thumb/8/86/Flag_of_Cote_d%27Ivoire.svg/20px-Flag_of_Cote_d%27Ivoire.svg.png", "http://fr.wikipedia.org/wiki/C%C3%B4te_d%27Ivoire" },    
    { "Croatie", "http://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/Flag_of_Croatia.svg/20px-Flag_of_Croatia.svg.png", "http://fr.wikipedia.org/wiki/Croatie" },    
    { "Cuba", "http://upload.wikimedia.org/wikipedia/commons/thumb/b/bd/Flag_of_Cuba.svg/20px-Flag_of_Cuba.svg.png", "http://fr.wikipedia.org/wiki/Cuba" },    
    { "Danemark", "http://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/Flag_of_Denmark.svg/20px-Flag_of_Denmark.svg.png", "http://fr.wikipedia.org/wiki/Danemark" },    
    { "Djibouti", "http://upload.wikimedia.org/wikipedia/commons/thumb/3/34/Flag_of_Djibouti.svg/20px-Flag_of_Djibouti.svg.png", "http://fr.wikipedia.org/wiki/Djibouti" },    
    { "République dominicaine", "http://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Flag_of_the_Dominican_Republic.svg/20px-Flag_of_the_Dominican_Republic.svg.png", "http://fr.wikipedia.org/wiki/R%C3%A9publique_dominicaine" },    
    { "Dominique", "http://upload.wikimedia.org/wikipedia/commons/thumb/c/c4/Flag_of_Dominica.svg/20px-Flag_of_Dominica.svg.png", "http://fr.wikipedia.org/wiki/Dominique_%28pays%29" },    
    { "Égypte", "http://upload.wikimedia.org/wikipedia/commons/thumb/f/fe/Flag_of_Egypt.svg/20px-Flag_of_Egypt.svg.png", "http://fr.wikipedia.org/wiki/%C3%89gypte" },    
    { "Émirats arabes unis", "http://upload.wikimedia.org/wikipedia/commons/thumb/c/cb/Flag_of_the_United_Arab_Emirates.svg/20px-Flag_of_the_United_Arab_Emirates.svg.png", "http://fr.wikipedia.org/wiki/%C3%89mirats_arabes_unis" },    
    { "Équateur", "http://upload.wikimedia.org/wikipedia/commons/thumb/e/e8/Flag_of_Ecuador.svg/20px-Flag_of_Ecuador.svg.png", "http://fr.wikipedia.org/wiki/%C3%89quateur_%28pays%29" },    
    { "Érythrée", "http://upload.wikimedia.org/wikipedia/commons/thumb/2/29/Flag_of_Eritrea.svg/20px-Flag_of_Eritrea.svg.png", "http://fr.wikipedia.org/wiki/%C3%89rythr%C3%A9e" },    
    { "Espagne", "http://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Flag_of_Spain.svg/20px-Flag_of_Spain.svg.png", "http://fr.wikipedia.org/wiki/Espagne" },    
    { "Estonie", "http://upload.wikimedia.org/wikipedia/commons/thumb/8/8f/Flag_of_Estonia.svg/20px-Flag_of_Estonia.svg.png", "http://fr.wikipedia.org/wiki/Estonie" },    
    { "États-Unis", "http://upload.wikimedia.org/wikipedia/commons/thumb/a/a4/Flag_of_the_United_States.svg/20px-Flag_of_the_United_States.svg.png", "http://fr.wikipedia.org/wiki/%C3%89tats-Unis" },    
    { "Éthiopie", "http://upload.wikimedia.org/wikipedia/commons/thumb/7/71/Flag_of_Ethiopia.svg/20px-Flag_of_Ethiopia.svg.png", "http://fr.wikipedia.org/wiki/%C3%89thiopie" },    
    { "Fidji", "http://upload.wikimedia.org/wikipedia/commons/thumb/b/ba/Flag_of_Fiji.svg/20px-Flag_of_Fiji.svg.png", "http://fr.wikipedia.org/wiki/Fidji" },    
    { "Finlande", "http://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Flag_of_Finland.svg/20px-Flag_of_Finland.svg.png", "http://fr.wikipedia.org/wiki/Finlande" },    
    { "France", "http://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Flag_of_France.svg/20px-Flag_of_France.svg.png", "http://fr.wikipedia.org/wiki/France" },    
    { "Gabon", "http://upload.wikimedia.org/wikipedia/commons/thumb/0/04/Flag_of_Gabon.svg/20px-Flag_of_Gabon.svg.png", "http://fr.wikipedia.org/wiki/Gabon" },    
    { "Gambie", "http://upload.wikimedia.org/wikipedia/commons/thumb/7/77/Flag_of_The_Gambia.svg/20px-Flag_of_The_Gambia.svg.png", "http://fr.wikipedia.org/wiki/Gambie" },    
    { "Géorgie", "http://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/Flag_of_Georgia.svg/20px-Flag_of_Georgia.svg.png", "http://fr.wikipedia.org/wiki/G%C3%A9orgie_%28pays%29" },    
    { "Ghana", "http://upload.wikimedia.org/wikipedia/commons/thumb/1/19/Flag_of_Ghana.svg/20px-Flag_of_Ghana.svg.png", "http://fr.wikipedia.org/wiki/Ghana" },    
    { "Grèce", "http://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Flag_of_Greece.svg/20px-Flag_of_Greece.svg.png", "http://fr.wikipedia.org/wiki/Gr%C3%A8ce" },    
    { "Grenade", "http://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Flag_of_Grenada.svg/20px-Flag_of_Grenada.svg.png", "http://fr.wikipedia.org/wiki/Grenade_%28pays%29" },    
    { "Guatemala", "http://upload.wikimedia.org/wikipedia/commons/thumb/e/ec/Flag_of_Guatemala.svg/20px-Flag_of_Guatemala.svg.png", "http://fr.wikipedia.org/wiki/Guatemala" },    
    { "Guinée", "http://upload.wikimedia.org/wikipedia/commons/thumb/e/ed/Flag_of_Guinea.svg/20px-Flag_of_Guinea.svg.png", "http://fr.wikipedia.org/wiki/Guin%C3%A9e" },    
    { "Guinée-Bissau", "http://upload.wikimedia.org/wikipedia/commons/thumb/0/01/Flag_of_Guinea-Bissau.svg/20px-Flag_of_Guinea-Bissau.svg.png", "http://fr.wikipedia.org/wiki/Guin%C3%A9e-Bissau" },    
    { "Guinée équatoriale", "http://upload.wikimedia.org/wikipedia/commons/thumb/3/31/Flag_of_Equatorial_Guinea.svg/20px-Flag_of_Equatorial_Guinea.svg.png", "http://fr.wikipedia.org/wiki/Guin%C3%A9e_%C3%A9quatoriale" },    
    { "Guyana", "http://upload.wikimedia.org/wikipedia/commons/thumb/9/99/Flag_of_Guyana.svg/20px-Flag_of_Guyana.svg.png", "http://fr.wikipedia.org/wiki/Guyana" },    
    { "Haïti", "http://upload.wikimedia.org/wikipedia/commons/thumb/5/56/Flag_of_Haiti.svg/20px-Flag_of_Haiti.svg.png", "http://fr.wikipedia.org/wiki/Ha%C3%AFti" },    
    { "Honduras", "http://upload.wikimedia.org/wikipedia/commons/thumb/8/82/Flag_of_Honduras.svg/20px-Flag_of_Honduras.svg.png", "http://fr.wikipedia.org/wiki/Honduras" },    
    { "Hongrie", "http://upload.wikimedia.org/wikipedia/commons/thumb/c/c1/Flag_of_Hungary.svg/20px-Flag_of_Hungary.svg.png", "http://fr.wikipedia.org/wiki/Hongrie" },    
    { "Inde", "http://upload.wikimedia.org/wikipedia/commons/thumb/4/41/Flag_of_India.svg/20px-Flag_of_India.svg.png", "http://fr.wikipedia.org/wiki/Inde" },    
    { "Indonésie", "http://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Flag_of_Indonesia.svg/20px-Flag_of_Indonesia.svg.png", "http://fr.wikipedia.org/wiki/Indon%C3%A9sie" },    
    { "Irak", "http://upload.wikimedia.org/wikipedia/commons/thumb/f/f6/Flag_of_Iraq.svg/20px-Flag_of_Iraq.svg.png", "http://fr.wikipedia.org/wiki/Irak" },    
    { "Iran", "http://upload.wikimedia.org/wikipedia/commons/thumb/c/ca/Flag_of_Iran.svg/20px-Flag_of_Iran.svg.png", "http://fr.wikipedia.org/wiki/Iran" },    
    { "Irlande", "http://upload.wikimedia.org/wikipedia/commons/thumb/4/45/Flag_of_Ireland.svg/20px-Flag_of_Ireland.svg.png", "http://fr.wikipedia.org/wiki/Irlande_%28pays%29" },    
    { "Islande", "http://upload.wikimedia.org/wikipedia/commons/thumb/c/ce/Flag_of_Iceland.svg/20px-Flag_of_Iceland.svg.png", "http://fr.wikipedia.org/wiki/Islande" },    
    { "Israël", "http://upload.wikimedia.org/wikipedia/commons/thumb/d/d4/Flag_of_Israel.svg/20px-Flag_of_Israel.svg.png", "http://fr.wikipedia.org/wiki/Isra%C3%ABl" },    
    { "Italie", "http://upload.wikimedia.org/wikipedia/commons/thumb/0/03/Flag_of_Italy.svg/20px-Flag_of_Italy.svg.png", "http://fr.wikipedia.org/wiki/Italie" },    
    { "Jamaïque", "http://upload.wikimedia.org/wikipedia/commons/thumb/0/0a/Flag_of_Jamaica.svg/20px-Flag_of_Jamaica.svg.png", "http://fr.wikipedia.org/wiki/Jama%C3%AFque" },    
    { "Japon", "http://upload.wikimedia.org/wikipedia/commons/thumb/9/9e/Flag_of_Japan.svg/20px-Flag_of_Japan.svg.png", "http://fr.wikipedia.org/wiki/Japon" },    
    { "Jordanie", "http://upload.wikimedia.org/wikipedia/commons/thumb/c/c0/Flag_of_Jordan.svg/20px-Flag_of_Jordan.svg.png", "http://fr.wikipedia.org/wiki/Jordanie" },    
    { "Kazakhstan", "http://upload.wikimedia.org/wikipedia/commons/thumb/d/d3/Flag_of_Kazakhstan.svg/20px-Flag_of_Kazakhstan.svg.png", "http://fr.wikipedia.org/wiki/Kazakhstan" },    
    { "Kenya", "http://upload.wikimedia.org/wikipedia/commons/thumb/4/49/Flag_of_Kenya.svg/20px-Flag_of_Kenya.svg.png", "http://fr.wikipedia.org/wiki/Kenya" },    
    { "Kirghizistan", "http://upload.wikimedia.org/wikipedia/commons/thumb/c/c7/Flag_of_Kyrgyzstan.svg/20px-Flag_of_Kyrgyzstan.svg.png", "http://fr.wikipedia.org/wiki/Kirghizie" },    
    { "Kiribati", "http://upload.wikimedia.org/wikipedia/commons/thumb/d/d3/Flag_of_Kiribati.svg/20px-Flag_of_Kiribati.svg.png", "http://fr.wikipedia.org/wiki/Kiribati" },    
    { "Koweït", "http://upload.wikimedia.org/wikipedia/commons/thumb/a/aa/Flag_of_Kuwait.svg/20px-Flag_of_Kuwait.svg.png", "http://fr.wikipedia.org/wiki/Kowe%C3%AFt" },    
    { "Laos", "http://upload.wikimedia.org/wikipedia/commons/thumb/5/56/Flag_of_Laos.svg/20px-Flag_of_Laos.svg.png", "http://fr.wikipedia.org/wiki/Laos" },    
    { "Lesotho", "http://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/Flag_of_Lesotho.svg/20px-Flag_of_Lesotho.svg.png", "http://fr.wikipedia.org/wiki/Lesotho" },    
    { "Lettonie", "http://upload.wikimedia.org/wikipedia/commons/thumb/8/84/Flag_of_Latvia.svg/20px-Flag_of_Latvia.svg.png", "http://fr.wikipedia.org/wiki/Lettonie" },    
    { "Liban", "http://upload.wikimedia.org/wikipedia/commons/thumb/5/59/Flag_of_Lebanon.svg/20px-Flag_of_Lebanon.svg.png", "http://fr.wikipedia.org/wiki/Liban" },    
    { "Libéria", "http://upload.wikimedia.org/wikipedia/commons/thumb/b/b8/Flag_of_Liberia.svg/20px-Flag_of_Liberia.svg.png", "http://fr.wikipedia.org/wiki/Liberia" },    
    { "Libye", "http://upload.wikimedia.org/wikipedia/commons/thumb/0/05/Flag_of_Libya.svg/20px-Flag_of_Libya.svg.png", "http://fr.wikipedia.org/wiki/Libye" },    
    { "Liechtenstein", "http://upload.wikimedia.org/wikipedia/commons/thumb/4/47/Flag_of_Liechtenstein.svg/20px-Flag_of_Liechtenstein.svg.png", "http://fr.wikipedia.org/wiki/Liechtenstein" },    
    { "Lituanie", "http://upload.wikimedia.org/wikipedia/commons/thumb/1/11/Flag_of_Lithuania.svg/20px-Flag_of_Lithuania.svg.png", "http://fr.wikipedia.org/wiki/Lituanie" },    
    { "Luxembourg", "http://upload.wikimedia.org/wikipedia/commons/thumb/d/da/Flag_of_Luxembourg.svg/20px-Flag_of_Luxembourg.svg.png", "http://fr.wikipedia.org/wiki/Luxembourg_%28pays%29" },    
    { "Macédoine", "http://upload.wikimedia.org/wikipedia/commons/thumb/f/f8/Flag_of_Macedonia.svg/20px-Flag_of_Macedonia.svg.png", "http://fr.wikipedia.org/wiki/Mac%C3%A9doine_%28pays%29" },    
    { "Madagascar", "http://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Flag_of_Madagascar.svg/20px-Flag_of_Madagascar.svg.png", "http://fr.wikipedia.org/wiki/Madagascar" },    
    { "Malaisie", "http://upload.wikimedia.org/wikipedia/commons/thumb/6/66/Flag_of_Malaysia.svg/20px-Flag_of_Malaysia.svg.png", "http://fr.wikipedia.org/wiki/Malaisie" },    
    { "Malawi", "http://upload.wikimedia.org/wikipedia/commons/thumb/d/d1/Flag_of_Malawi.svg/20px-Flag_of_Malawi.svg.png", "http://fr.wikipedia.org/wiki/Malawi" },    
    { "Maldives", "http://upload.wikimedia.org/wikipedia/commons/thumb/0/0f/Flag_of_Maldives.svg/20px-Flag_of_Maldives.svg.png", "http://fr.wikipedia.org/wiki/Maldives" },    
    { "Mali", "http://upload.wikimedia.org/wikipedia/commons/thumb/9/92/Flag_of_Mali.svg/20px-Flag_of_Mali.svg.png", "http://fr.wikipedia.org/wiki/Mali" },    
    { "Malte", "http://upload.wikimedia.org/wikipedia/commons/thumb/7/73/Flag_of_Malta.svg/20px-Flag_of_Malta.svg.png", "http://fr.wikipedia.org/wiki/Malte" },    
    { "Maroc", "http://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Flag_of_Morocco.svg/20px-Flag_of_Morocco.svg.png", "http://fr.wikipedia.org/wiki/Maroc" },    
    { "Îles Marshall", "http://upload.wikimedia.org/wikipedia/commons/thumb/2/2e/Flag_of_the_Marshall_Islands.svg/20px-Flag_of_the_Marshall_Islands.svg.png", "http://fr.wikipedia.org/wiki/Marshall_%28pays%29" },    
    { "Maurice", "http://upload.wikimedia.org/wikipedia/commons/thumb/7/77/Flag_of_Mauritius.svg/20px-Flag_of_Mauritius.svg.png", "http://fr.wikipedia.org/wiki/Maurice_%28pays%29" },    
    { "Mauritanie", "http://upload.wikimedia.org/wikipedia/commons/thumb/4/43/Flag_of_Mauritania.svg/20px-Flag_of_Mauritania.svg.png", "http://fr.wikipedia.org/wiki/Mauritanie" },    
    { "Mexique", "http://upload.wikimedia.org/wikipedia/commons/thumb/f/fc/Flag_of_Mexico.svg/20px-Flag_of_Mexico.svg.png", "http://fr.wikipedia.org/wiki/Mexique" },    
    { "Micronésie", "http://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Flag_of_Federated_States_of_Micronesia.svg/20px-Flag_of_Federated_States_of_Micronesia.svg.png", "http://fr.wikipedia.org/wiki/Micron%C3%A9sie_%28pays%29" },    
    { "Moldavie", "http://upload.wikimedia.org/wikipedia/commons/thumb/2/27/Flag_of_Moldova.svg/20px-Flag_of_Moldova.svg.png", "http://fr.wikipedia.org/wiki/R%C3%A9publique_de_Moldavie" },    
    { "Monaco", "http://upload.wikimedia.org/wikipedia/commons/thumb/e/ea/Flag_of_Monaco.svg/20px-Flag_of_Monaco.svg.png", "http://fr.wikipedia.org/wiki/Monaco" },    
    { "Mongolie", "http://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Flag_of_Mongolia.svg/20px-Flag_of_Mongolia.svg.png", "http://fr.wikipedia.org/wiki/Mongolie" },    
    { "Monténégro", "http://upload.wikimedia.org/wikipedia/commons/thumb/6/64/Flag_of_Montenegro.svg/20px-Flag_of_Montenegro.svg.png", "http://fr.wikipedia.org/wiki/Mont%C3%A9n%C3%A9gro" },    
    { "Mozambique", "http://upload.wikimedia.org/wikipedia/commons/thumb/d/d0/Flag_of_Mozambique.svg/20px-Flag_of_Mozambique.svg.png", "http://fr.wikipedia.org/wiki/Mozambique" },    
    { "Namibie", "http://upload.wikimedia.org/wikipedia/commons/thumb/0/00/Flag_of_Namibia.svg/20px-Flag_of_Namibia.svg.png", "http://fr.wikipedia.org/wiki/Namibie" },    
    { "Nauru", "http://upload.wikimedia.org/wikipedia/commons/thumb/3/30/Flag_of_Nauru.svg/20px-Flag_of_Nauru.svg.png", "http://fr.wikipedia.org/wiki/Nauru" },    
    { "Népal", "http://upload.wikimedia.org/wikipedia/commons/thumb/9/9b/Flag_of_Nepal.svg/20px-Flag_of_Nepal.svg.png", "http://fr.wikipedia.org/wiki/N%C3%A9pal" },    
    { "Nicaragua", "http://upload.wikimedia.org/wikipedia/commons/thumb/1/19/Flag_of_Nicaragua.svg/20px-Flag_of_Nicaragua.svg.png", "http://fr.wikipedia.org/wiki/Nicaragua" },    
    { "Niger", "http://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/Flag_of_Niger.svg/20px-Flag_of_Niger.svg.png", "http://fr.wikipedia.org/wiki/Niger" },    
    { "Nigeria", "http://upload.wikimedia.org/wikipedia/commons/thumb/7/79/Flag_of_Nigeria.svg/20px-Flag_of_Nigeria.svg.png", "http://fr.wikipedia.org/wiki/Nigeria" },    
    { "Norvège", "http://upload.wikimedia.org/wikipedia/commons/thumb/d/d9/Flag_of_Norway.svg/20px-Flag_of_Norway.svg.png", "http://fr.wikipedia.org/wiki/Norv%C3%A8ge" },    
    { "Nouvelle-Zélande", "http://upload.wikimedia.org/wikipedia/commons/thumb/3/3e/Flag_of_New_Zealand.svg/20px-Flag_of_New_Zealand.svg.png", "http://fr.wikipedia.org/wiki/Nouvelle-Z%C3%A9lande" },    
    { "Oman", "http://upload.wikimedia.org/wikipedia/commons/thumb/d/dd/Flag_of_Oman.svg/20px-Flag_of_Oman.svg.png", "http://fr.wikipedia.org/wiki/Oman" },    
    { "Ouganda", "http://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/Flag_of_Uganda.svg/20px-Flag_of_Uganda.svg.png", "http://fr.wikipedia.org/wiki/Ouganda" },    
    { "Ouzbékistan", "http://upload.wikimedia.org/wikipedia/commons/thumb/8/84/Flag_of_Uzbekistan.svg/20px-Flag_of_Uzbekistan.svg.png", "http://fr.wikipedia.org/wiki/Ouzb%C3%A9kistan" },    
    { "Pakistan", "http://upload.wikimedia.org/wikipedia/commons/thumb/3/32/Flag_of_Pakistan.svg/20px-Flag_of_Pakistan.svg.png", "http://fr.wikipedia.org/wiki/Pakistan" },    
    { "Palaos", "http://upload.wikimedia.org/wikipedia/commons/thumb/4/48/Flag_of_Palau.svg/20px-Flag_of_Palau.svg.png", "http://fr.wikipedia.org/wiki/Palaos" },    
    { "Panamà", "http://upload.wikimedia.org/wikipedia/commons/thumb/a/ab/Flag_of_Panama.svg/20px-Flag_of_Panama.svg.png", "http://fr.wikipedia.org/wiki/Panama" },    
    { "Papouasie-Nouvelle-Guinée", "http://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/Flag_of_Papua_New_Guinea.svg/20px-Flag_of_Papua_New_Guinea.svg.png", "http://fr.wikipedia.org/wiki/Papouasie-Nouvelle-Guin%C3%A9e" },    
    { "Paraguay", "http://upload.wikimedia.org/wikipedia/commons/thumb/2/27/Flag_of_Paraguay.svg/20px-Flag_of_Paraguay.svg.png", "http://fr.wikipedia.org/wiki/Paraguay" },    
    { "Pays-Bas", "http://upload.wikimedia.org/wikipedia/commons/thumb/2/20/Flag_of_the_Netherlands.svg/20px-Flag_of_the_Netherlands.svg.png", "http://fr.wikipedia.org/wiki/Pays-Bas" },    
    { "Pérou", "http://upload.wikimedia.org/wikipedia/commons/thumb/c/cf/Flag_of_Peru.svg/20px-Flag_of_Peru.svg.png", "http://fr.wikipedia.org/wiki/P%C3%A9rou" },    
    { "Philippines", "http://upload.wikimedia.org/wikipedia/commons/thumb/9/99/Flag_of_the_Philippines.svg/20px-Flag_of_the_Philippines.svg.png", "http://fr.wikipedia.org/wiki/Philippines" },    
    { "Pologne", "http://upload.wikimedia.org/wikipedia/commons/thumb/1/12/Flag_of_Poland.svg/20px-Flag_of_Poland.svg.png", "http://fr.wikipedia.org/wiki/Pologne" },    
    { "Portugal", "http://upload.wikimedia.org/wikipedia/commons/thumb/5/5c/Flag_of_Portugal.svg/20px-Flag_of_Portugal.svg.png", "http://fr.wikipedia.org/wiki/Portugal" },    
    { "Qatar", "http://upload.wikimedia.org/wikipedia/commons/thumb/6/65/Flag_of_Qatar.svg/20px-Flag_of_Qatar.svg.png", "http://fr.wikipedia.org/wiki/Qatar" },    
    { "Roumanie", "http://upload.wikimedia.org/wikipedia/commons/thumb/7/73/Flag_of_Romania.svg/20px-Flag_of_Romania.svg.png", "http://fr.wikipedia.org/wiki/Roumanie" },    
    { "Royaume-Uni", "http://upload.wikimedia.org/wikipedia/commons/thumb/a/ae/Flag_of_the_United_Kingdom.svg/20px-Flag_of_the_United_Kingdom.svg.png", "http://fr.wikipedia.org/wiki/Royaume-Uni" },    
    { "Russie", "http://upload.wikimedia.org/wikipedia/commons/thumb/f/f3/Flag_of_Russia.svg/20px-Flag_of_Russia.svg.png", "http://fr.wikipedia.org/wiki/Russie" },    
    { "Rwanda", "http://upload.wikimedia.org/wikipedia/commons/thumb/1/17/Flag_of_Rwanda.svg/20px-Flag_of_Rwanda.svg.png", "http://fr.wikipedia.org/wiki/Rwanda" },    
    { "Saint-Christophe-et-Niévès", "http://upload.wikimedia.org/wikipedia/commons/thumb/f/fe/Flag_of_Saint_Kitts_and_Nevis.svg/20px-Flag_of_Saint_Kitts_and_Nevis.svg.png", "http://fr.wikipedia.org/wiki/Saint-Christophe-et-Ni%C3%A9v%C3%A8s" },    
    { "Sainte-Lucie", "http://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Flag_of_Saint_Lucia.svg/20px-Flag_of_Saint_Lucia.svg.png", "http://fr.wikipedia.org/wiki/Sainte-Lucie" },    
    { "Saint-Marin", "http://upload.wikimedia.org/wikipedia/commons/thumb/b/b1/Flag_of_San_Marino.svg/20px-Flag_of_San_Marino.svg.png", "http://fr.wikipedia.org/wiki/Saint-Marin" },    
    { "Saint-Vincent-et-les Grenadines", "http://upload.wikimedia.org/wikipedia/commons/thumb/6/6d/Flag_of_Saint_Vincent_and_the_Grenadines.svg/20px-Flag_of_Saint_Vincent_and_the_Grenadines.svg.png", "http://fr.wikipedia.org/wiki/Saint-Vincent-et-les_Grenadines" },    
    { "Îles Salomon", "http://upload.wikimedia.org/wikipedia/commons/thumb/7/74/Flag_of_the_Solomon_Islands.svg/20px-Flag_of_the_Solomon_Islands.svg.png", "http://fr.wikipedia.org/wiki/Salomon_%28pays%29" },    
    { "Salvador", "http://upload.wikimedia.org/wikipedia/commons/thumb/3/34/Flag_of_El_Salvador.svg/20px-Flag_of_El_Salvador.svg.png", "http://fr.wikipedia.org/wiki/Salvador" },    
    { "Samoa", "http://upload.wikimedia.org/wikipedia/commons/thumb/3/31/Flag_of_Samoa.svg/21px-Flag_of_Samoa.svg.png", "http://fr.wikipedia.org/wiki/Samoa" },    
    { "São Tomé-et-Principe", "http://upload.wikimedia.org/wikipedia/commons/thumb/4/4f/Flag_of_Sao_Tome_and_Principe.svg/20px-Flag_of_Sao_Tome_and_Principe.svg.png", "http://fr.wikipedia.org/wiki/Sao_Tom%C3%A9-et-Principe" },    
    { "Sénégal", "http://upload.wikimedia.org/wikipedia/commons/thumb/f/fd/Flag_of_Senegal.svg/20px-Flag_of_Senegal.svg.png", "http://fr.wikipedia.org/wiki/S%C3%A9n%C3%A9gal" },    
    { "Serbie", "http://upload.wikimedia.org/wikipedia/commons/thumb/f/ff/Flag_of_Serbia.svg/20px-Flag_of_Serbia.svg.png", "http://fr.wikipedia.org/wiki/Serbie" },    
    { "Seychelles", "http://upload.wikimedia.org/wikipedia/commons/thumb/9/92/Flag_of_the_Seychelles.svg/20px-Flag_of_the_Seychelles.svg.png", "http://fr.wikipedia.org/wiki/Seychelles" },    
    { "Sierra Leone", "http://upload.wikimedia.org/wikipedia/commons/thumb/1/17/Flag_of_Sierra_Leone.svg/20px-Flag_of_Sierra_Leone.svg.png", "http://fr.wikipedia.org/wiki/Sierra_Leone" },    
    { "Singapour", "http://upload.wikimedia.org/wikipedia/commons/thumb/4/48/Flag_of_Singapore.svg/20px-Flag_of_Singapore.svg.png", "http://fr.wikipedia.org/wiki/Singapour" },    
    { "Slovaquie", "http://upload.wikimedia.org/wikipedia/commons/thumb/e/e6/Flag_of_Slovakia.svg/20px-Flag_of_Slovakia.svg.png", "http://fr.wikipedia.org/wiki/Slovaquie" },    
    { "Slovénie", "http://upload.wikimedia.org/wikipedia/commons/thumb/f/f0/Flag_of_Slovenia.svg/20px-Flag_of_Slovenia.svg.png", "http://fr.wikipedia.org/wiki/Slov%C3%A9nie" },    
    { "Somalie", "http://upload.wikimedia.org/wikipedia/commons/thumb/a/a0/Flag_of_Somalia.svg/20px-Flag_of_Somalia.svg.png", "http://fr.wikipedia.org/wiki/Somalie" },    
    { "Soudan", "http://upload.wikimedia.org/wikipedia/commons/thumb/0/01/Flag_of_Sudan.svg/20px-Flag_of_Sudan.svg.png", "http://fr.wikipedia.org/wiki/Soudan" },    
    { "Sri Lanka", "http://upload.wikimedia.org/wikipedia/commons/thumb/1/11/Flag_of_Sri_Lanka.svg/20px-Flag_of_Sri_Lanka.svg.png", "http://fr.wikipedia.org/wiki/Sri_Lanka" },    
    { "Suède", "http://upload.wikimedia.org/wikipedia/commons/thumb/4/4c/Flag_of_Sweden.svg/20px-Flag_of_Sweden.svg.png", "http://fr.wikipedia.org/wiki/Su%C3%A8de" },    
    { "", "", "http://fr.wikipedia.org/wiki/Suisse" },    
    { "Suriname", "http://upload.wikimedia.org/wikipedia/commons/thumb/6/60/Flag_of_Suriname.svg/20px-Flag_of_Suriname.svg.png", "http://fr.wikipedia.org/wiki/Suriname" },    
    { "Swaziland", "http://upload.wikimedia.org/wikipedia/commons/thumb/1/1e/Flag_of_Swaziland.svg/20px-Flag_of_Swaziland.svg.png", "http://fr.wikipedia.org/wiki/Swaziland" },    
    { "Syrie", "http://upload.wikimedia.org/wikipedia/commons/thumb/5/53/Flag_of_Syria.svg/20px-Flag_of_Syria.svg.png", "http://fr.wikipedia.org/wiki/Syrie" },    
    { "Tadjikistan", "http://upload.wikimedia.org/wikipedia/commons/thumb/d/d0/Flag_of_Tajikistan.svg/20px-Flag_of_Tajikistan.svg.png", "http://fr.wikipedia.org/wiki/Tadjikistan" },    
    { "Tanzanie", "http://upload.wikimedia.org/wikipedia/commons/thumb/3/38/Flag_of_Tanzania.svg/20px-Flag_of_Tanzania.svg.png", "http://fr.wikipedia.org/wiki/Tanzanie" },    
    { "Tchad", "http://upload.wikimedia.org/wikipedia/commons/thumb/4/4b/Flag_of_Chad.svg/20px-Flag_of_Chad.svg.png", "http://fr.wikipedia.org/wiki/Tchad" },    
    { "République tchèque", "http://upload.wikimedia.org/wikipedia/commons/thumb/c/cb/Flag_of_the_Czech_Republic.svg/20px-Flag_of_the_Czech_Republic.svg.png", "http://fr.wikipedia.org/wiki/R%C3%A9publique_tch%C3%A8que" },    
    { "Thaïlande", "http://upload.wikimedia.org/wikipedia/commons/thumb/a/a9/Flag_of_Thailand.svg/20px-Flag_of_Thailand.svg.png", "http://fr.wikipedia.org/wiki/Tha%C3%AFlande" },    
    { "Timor oriental", "http://upload.wikimedia.org/wikipedia/commons/thumb/2/26/Flag_of_East_Timor.svg/20px-Flag_of_East_Timor.svg.png", "http://fr.wikipedia.org/wiki/Timor_oriental" },    
    { "Togo", "http://upload.wikimedia.org/wikipedia/commons/thumb/6/68/Flag_of_Togo.svg/20px-Flag_of_Togo.svg.png", "http://fr.wikipedia.org/wiki/Togo" },    
    { "Tonga", "http://upload.wikimedia.org/wikipedia/commons/thumb/9/9a/Flag_of_Tonga.svg/20px-Flag_of_Tonga.svg.png", "http://fr.wikipedia.org/wiki/Tonga" },    
    { "Trinité-et-Tobago", "http://upload.wikimedia.org/wikipedia/commons/thumb/6/64/Flag_of_Trinidad_and_Tobago.svg/20px-Flag_of_Trinidad_and_Tobago.svg.png", "http://fr.wikipedia.org/wiki/Trinit%C3%A9-et-Tobago" },    
    { "Tunisie", "http://upload.wikimedia.org/wikipedia/commons/thumb/c/ce/Flag_of_Tunisia.svg/20px-Flag_of_Tunisia.svg.png", "http://fr.wikipedia.org/wiki/Tunisie" },    
    { "Turkménistan", "http://upload.wikimedia.org/wikipedia/commons/thumb/1/1b/Flag_of_Turkmenistan.svg/20px-Flag_of_Turkmenistan.svg.png", "http://fr.wikipedia.org/wiki/Turkm%C3%A9nistan" },    
    { "Turquie", "http://upload.wikimedia.org/wikipedia/commons/thumb/b/b4/Flag_of_Turkey.svg/20px-Flag_of_Turkey.svg.png", "http://fr.wikipedia.org/wiki/Turquie" },    
    { "Tuvalu", "http://upload.wikimedia.org/wikipedia/commons/thumb/3/38/Flag_of_Tuvalu.svg/20px-Flag_of_Tuvalu.svg.png", "http://fr.wikipedia.org/wiki/Tuvalu" },    
    { "Ukraine", "http://upload.wikimedia.org/wikipedia/commons/thumb/4/49/Flag_of_Ukraine.svg/20px-Flag_of_Ukraine.svg.png", "http://fr.wikipedia.org/wiki/Ukraine" },    
    { "Uruguay", "http://upload.wikimedia.org/wikipedia/commons/thumb/f/fe/Flag_of_Uruguay.svg/20px-Flag_of_Uruguay.svg.png", "http://fr.wikipedia.org/wiki/Uruguay" },    
    { "Vanuatu", "http://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Flag_of_Vanuatu.svg/20px-Flag_of_Vanuatu.svg.png", "http://fr.wikipedia.org/wiki/Vanuatu" },    
    { "Vatican", "http://upload.wikimedia.org/wikipedia/commons/thumb/0/00/Flag_of_the_Vatican_City.svg/18px-Flag_of_the_Vatican_City.svg.png", "http://fr.wikipedia.org/wiki/Vatican" },    
    { "Venezuela", "http://upload.wikimedia.org/wikipedia/commons/thumb/7/7b/Flag_of_Venezuela_%28state%29.svg/20px-Flag_of_Venezuela_%28state%29.svg.png", "http://fr.wikipedia.org/wiki/Venezuela" },    
    { "Viêt Nam", "http://upload.wikimedia.org/wikipedia/commons/thumb/2/21/Flag_of_Vietnam.svg/20px-Flag_of_Vietnam.svg.png", "http://fr.wikipedia.org/wiki/Vi%C3%AAt_Nam" },    
    { "Yémen", "http://upload.wikimedia.org/wikipedia/commons/thumb/8/89/Flag_of_Yemen.svg/20px-Flag_of_Yemen.svg.png", "http://fr.wikipedia.org/wiki/Y%C3%A9men" },    
    { "Zambie", "http://upload.wikimedia.org/wikipedia/commons/thumb/0/06/Flag_of_Zambia.svg/20px-Flag_of_Zambia.svg.png", "http://fr.wikipedia.org/wiki/Zambie" },    
    { "Zimbabwe", "http://upload.wikimedia.org/wikipedia/commons/thumb/6/6a/Flag_of_Zimbabwe.svg/20px-Flag_of_Zimbabwe.svg.png", "http://fr.wikipedia.org/wiki/Zimbabwe" }
  };  
}
