all :
	pdflatex RapportTravauxFusciaUnisciel
	bibtex RapportTravauxFusciaUnisciel
	pdflatex RapportTravauxFusciaUnisciel
	pdflatex RapportTravauxFusciaUnisciel
	rm -f *.aux *.bbl *.blg *.brf *.log *.out
