title="Pour s’approprier sur un exemple 2D les différents éléments caractéristiques d’un graphe, en vue de saisir les algorithmes qui en font usage."
author="Cécile Picard-Limpens <ccl.picard@gmail.com>"
icon="logo.png"
processing = "true"
width="900"
height="500"
source_url="http://www.openprocessing.org/portal/?userID=8553"
